name: Live Local - Think Global
favicon: null
layout_spectrum: 0.66603
typography_spectrum: 0.66214
title: My perspective and opinion sharing with the wider masses
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#81888b'
    - '#8a9dc9'
    - '#000000'
    - '#503224'
    - '#a5b6db'
  brandStrength: 0.9985646456480026
  lightness: 0.03784182877279818
  saturation: 0.5623292250093073
  rhythmicContrast: 0.5840192893519998
purpose: []
